baseurl: "/VNG-Realisatie"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor documentatie
    subnav:
      - title: Algemeen
        url: https://melsk-r.github.io/Imvertor-organisaties/
        path: /
  - title: VNG Realisatie specifieke documentatie
    subnav:
      - title: Inleiding
        path: /index
      - title: Installatie
        path: /installatie
      - title: Begrippen
        path: /begrippen
      - title: Het drie-lagen model
        path: /het-3-lagen-model
      - title: De nieuwe werkwijze
        path: /de-nieuwe-werkwijze
      - title: Handreikingen
        path: /handreikingen
      - title: Wetenswaardigheden en specials
        path: /wetenswaardigheden-en-specials
      - title: Tagged Values
        path: /tagged-values
      - title: Veel voorkomende foutens
        path: /veel-voorkomende-fouten
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
# remote_theme: melsk-r/Imvertor-jekyll-theme
remote_theme: https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal

github: melsk-r/VNG-Realisatie

theme: jekyll-theme-time-machine

project_name: /Imvertor
